#!/usr/bin/env bash
# Fetch SPDX license data for license validation
# Clean room approach: all data stored in vendor_external/spdx/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPDX_DIR="${SCRIPT_DIR}/spdx"

# SPDX License List version and sources
SPDX_VERSION="3.23"
SPDX_LICENSES_URL="https://raw.githubusercontent.com/spdx/license-list-data/v${SPDX_VERSION}/json/licenses.json"
SPDX_EXCEPTIONS_URL="https://raw.githubusercontent.com/spdx/license-list-data/v${SPDX_VERSION}/json/exceptions.json"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

mkdir -p "${SPDX_DIR}"

fetch_licenses() {
    log_info "Fetching SPDX license list v${SPDX_VERSION}..."

    curl -sL -o "${SPDX_DIR}/licenses.json" "${SPDX_LICENSES_URL}" || {
        log_error "Failed to download licenses.json"
        return 1
    }

    log_info "Downloaded licenses.json"
}

fetch_exceptions() {
    log_info "Fetching SPDX license exceptions..."

    curl -sL -o "${SPDX_DIR}/exceptions.json" "${SPDX_EXCEPTIONS_URL}" || {
        log_warn "Failed to download exceptions.json (optional)"
        return 0
    }

    log_info "Downloaded exceptions.json"
}

generate_go_map() {
    log_info "Generating Go license map..."

    # Parse JSON and generate Go code
    python3 - << 'PYTHON_SCRIPT' > "${SPDX_DIR}/spdx_licenses.go"
import json
import sys

with open("${SPDX_DIR}/licenses.json") as f:
    data = json.load(f)

licenses = data.get("licenses", [])

print("""// Code generated by fetch_spdx.sh. DO NOT EDIT.

package spdx

// SPDXLicenses maps license IDs to their full names
var SPDXLicenses = map[string]string{""")

for lic in sorted(licenses, key=lambda x: x["licenseId"]):
    lid = lic["licenseId"]
    name = lic["name"].replace('"', '\\"')
    deprecated = lic.get("isDeprecatedLicenseId", False)
    if not deprecated:
        print(f'\t"{lid}": "{name}",')

print("}")

print("""

// IsValidSPDX returns true if the license ID is a valid SPDX identifier
func IsValidSPDX(id string) bool {
\t_, ok := SPDXLicenses[id]
\treturn ok
}""")
PYTHON_SCRIPT

    log_info "Generated spdx_licenses.go"
}

generate_json_map() {
    log_info "Generating simplified JSON map for runtime use..."

    python3 - "${SPDX_DIR}/licenses.json" "${SPDX_VERSION}" << 'PYTHON_SCRIPT' > "${SPDX_DIR}/spdx_licenses.json"
import json
import sys

licenses_file = sys.argv[1]
spdx_version = sys.argv[2]

with open(licenses_file) as f:
    data = json.load(f)

licenses = {}
for lic in data.get("licenses", []):
    if not lic.get("isDeprecatedLicenseId", False):
        licenses[lic["licenseId"]] = {
            "name": lic["name"],
            "osi_approved": lic.get("isOsiApproved", False),
            "fsf_libre": lic.get("isFsfLibre", False)
        }

output = {"licenses": licenses, "version": spdx_version}
print(json.dumps(output, indent=2, sort_keys=True))
PYTHON_SCRIPT

    log_info "Generated spdx_licenses.json"
}

generate_common_aliases() {
    log_info "Generating common license aliases..."

    cat > "${SPDX_DIR}/license_aliases.json" << 'EOF'
{
  "version": "1.0",
  "description": "Common license aliases mapped to SPDX identifiers",
  "aliases": {
    "Public Domain": "CC-PDDC",
    "public domain": "CC-PDDC",
    "PD": "CC-PDDC",
    "pd": "CC-PDDC",

    "GPL": "GPL-3.0-or-later",
    "GPLv3": "GPL-3.0-only",
    "GPLv3+": "GPL-3.0-or-later",
    "GPLv2": "GPL-2.0-only",
    "GPLv2+": "GPL-2.0-or-later",
    "LGPL": "LGPL-3.0-or-later",
    "LGPLv3": "LGPL-3.0-only",
    "LGPLv2.1": "LGPL-2.1-only",

    "MIT": "MIT",
    "MIT License": "MIT",
    "Expat": "MIT",

    "BSD": "BSD-3-Clause",
    "BSD-3": "BSD-3-Clause",
    "BSD 3-Clause": "BSD-3-Clause",
    "BSD-2": "BSD-2-Clause",
    "BSD 2-Clause": "BSD-2-Clause",
    "Simplified BSD": "BSD-2-Clause",
    "FreeBSD": "BSD-2-Clause-FreeBSD",

    "Apache": "Apache-2.0",
    "Apache 2": "Apache-2.0",
    "Apache 2.0": "Apache-2.0",
    "Apache License 2.0": "Apache-2.0",
    "ASL 2.0": "Apache-2.0",

    "CC0": "CC0-1.0",
    "CC0 1.0": "CC0-1.0",
    "CC-0": "CC0-1.0",

    "CC BY": "CC-BY-4.0",
    "CC BY 4.0": "CC-BY-4.0",
    "CC BY 3.0": "CC-BY-3.0",
    "Attribution": "CC-BY-4.0",
    "Creative Commons Attribution": "CC-BY-4.0",

    "CC BY-SA": "CC-BY-SA-4.0",
    "CC BY-SA 4.0": "CC-BY-SA-4.0",
    "CC BY-SA 3.0": "CC-BY-SA-3.0",

    "CC BY-NC": "CC-BY-NC-4.0",
    "CC BY-NC 4.0": "CC-BY-NC-4.0",
    "CC BY-NC 3.0": "CC-BY-NC-3.0",

    "CC BY-NC-SA": "CC-BY-NC-SA-4.0",
    "CC BY-NC-SA 4.0": "CC-BY-NC-SA-4.0",
    "CC BY-NC-SA 3.0": "CC-BY-NC-SA-3.0",

    "CC BY-NC-ND": "CC-BY-NC-ND-4.0",
    "CC BY-NC-ND 4.0": "CC-BY-NC-ND-4.0",
    "CC BY-NC-ND 3.0": "CC-BY-NC-ND-3.0",

    "CC BY-ND": "CC-BY-ND-4.0",
    "CC BY-ND 4.0": "CC-BY-ND-4.0",
    "CC BY-ND 3.0": "CC-BY-ND-3.0",

    "CDDL": "CDDL-1.0",
    "CDDL 1.0": "CDDL-1.0",
    "CDDL-1.1": "CDDL-1.1",

    "MPL": "MPL-2.0",
    "MPL 2.0": "MPL-2.0",
    "Mozilla Public License": "MPL-2.0",

    "ISC": "ISC",
    "ISC License": "ISC",

    "Unlicense": "Unlicense",
    "The Unlicense": "Unlicense",

    "WTFPL": "WTFPL",

    "Zlib": "Zlib",
    "zlib": "Zlib",
    "zlib/libpng": "Zlib",

    "Copyrighted": "LicenseRef-Copyrighted",
    "copyrighted": "LicenseRef-Copyrighted",
    "All Rights Reserved": "LicenseRef-Copyrighted",
    "Copyrighted; Permission to distribute granted to CrossWire": "LicenseRef-Copyrighted",
    "Copyrighted; free non-commercial distribution": "LicenseRef-Copyrighted-Free"
  }
}
EOF

    log_info "Generated license_aliases.json"
}

generate_checksums() {
    log_info "Generating checksums..."
    cd "${SPDX_DIR}"
    sha256sum *.json > checksums.sha256
    log_info "Checksums written to ${SPDX_DIR}/checksums.sha256"
}

# Main execution
log_info "SPDX License Fetcher - Clean Room Setup"
log_info "Target directory: ${SPDX_DIR}"
log_info "SPDX version: ${SPDX_VERSION}"

fetch_licenses
fetch_exceptions
generate_json_map
generate_common_aliases
generate_checksums

log_info "Done! SPDX data stored in ${SPDX_DIR}"
log_info ""
log_info "Files created:"
log_info "  - licenses.json (raw SPDX data)"
log_info "  - spdx_licenses.json (simplified for runtime)"
log_info "  - license_aliases.json (common name mappings)"
