// Code generated by testgen; DO NOT EDIT.

package sfm

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_SFM(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "\\id GEN\n\\h Genesis\n\\c 1\n\\p\n\\v 1 In the beginning God created the heavens and the earth.\n\\v 2 And the earth was without form, and void.\n",
		RoundTrip:         false,
		NegativeDetection: "This is plain text with no SFM markers at all.",
		ExpectedLossClass: "L1",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
