// Code generated by testgen; DO NOT EDIT.

package usx

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_USX(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<usx version=\"3.0\">\n  <book code=\"GEN\" style=\"id\">Genesis</book>\n  <chapter number=\"1\" style=\"c\" sid=\"GEN 1\"/>\n  <para style=\"p\">\n    <verse number=\"1\" style=\"v\" sid=\"GEN 1:1\"/>In the beginning God created the heavens and the earth.<verse eid=\"GEN 1:1\"/>\n  </para>\n  <chapter eid=\"GEN 1\"/>\n</usx>",
		RoundTrip:         false,
		NegativeDetection: "<?xml version=\"1.0\"?>\n<catalog><item>Not USX</item></catalog>",
		ExpectedLossClass: "L0",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
