// Command testgen generates format_generated_test.go files for each format
// directory that contains a testspec.json file.
//
// Usage:
//
//	go run ./tools/testgen
//
// Or via go:generate from core/formats/generate.go:
//
//	go generate ./core/formats/...
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// TestSpec mirrors the JSON spec files in each format directory.
type TestSpec struct {
	Name              string   `json:"name"`
	Package           string   `json:"package"`
	SampleContent     string   `json:"sample_content"`
	RoundTrip         bool     `json:"round_trip"`
	ExpectedLossClass string   `json:"expected_loss_class"`
	Extensions        []string `json:"extensions"`
	NegativeDetection string   `json:"negative_detection"`
	ExpectedIR        *IRSpec  `json:"expected_ir"`
	SkipTests         []string `json:"skip_tests"`
}

// IRSpec holds expected IR assertions.
type IRSpec struct {
	ID               string `json:"id"`
	MinDocuments     int    `json:"min_documents"`
	MinContentBlocks int    `json:"min_content_blocks"`
}

const generatedTemplate = `// Code generated by testgen; DO NOT EDIT.

package {{.Package}}

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_{{.Name}}(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:        Config,
		SampleContent: {{printf "%q" .SampleContent}},
		RoundTrip:     {{.RoundTrip}},
		NegativeDetection: {{printf "%q" .NegativeDetection}},
		ExpectedLossClass: {{printf "%q" .ExpectedLossClass}},
		SkipTests: []string{ {{- range $i, $s := .SkipTests}}{{if $i}}, {{end}}{{printf "%q" $s}}{{end -}} },
{{- if .ExpectedIR}}
		ExpectedIR: &ftesting.IRExpectations{
			ID:               {{printf "%q" .ExpectedIR.ID}},
			MinDocuments:     {{.ExpectedIR.MinDocuments}},
			MinContentBlocks: {{.ExpectedIR.MinContentBlocks}},
		},
{{- end}}
	}
}
`

func main() {
	root := findProjectRoot()
	formatsDir := filepath.Join(root, "core", "formats")

	specs, err := filepath.Glob(filepath.Join(formatsDir, "*", "testspec.json"))
	if err != nil {
		fatalf("glob: %v", err)
	}

	if len(specs) == 0 {
		fatalf("no testspec.json files found under %s", formatsDir)
	}

	tmpl, err := template.New("test").Parse(generatedTemplate)
	if err != nil {
		fatalf("template parse: %v", err)
	}

	var generated int
	for _, specPath := range specs {
		if err := processSpec(tmpl, specPath); err != nil {
			fatalf("%s: %v", specPath, err)
		}
		generated++
	}

	fmt.Printf("testgen: generated %d test files\n", generated)
}

func processSpec(tmpl *template.Template, specPath string) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("read spec: %w", err)
	}

	var spec TestSpec
	if err := json.Unmarshal(data, &spec); err != nil {
		return fmt.Errorf("parse spec: %w", err)
	}

	if spec.Name == "" || spec.Package == "" {
		return fmt.Errorf("name and package are required fields")
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, &spec); err != nil {
		return fmt.Errorf("template execute: %w", err)
	}

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		return fmt.Errorf("gofmt: %w\ngenerated source:\n%s", err, buf.String())
	}

	outPath := filepath.Join(filepath.Dir(specPath), "format_generated_test.go")
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		return fmt.Errorf("write: %w", err)
	}

	fmt.Printf("  %s\n", outPath)
	return nil
}

// findProjectRoot walks up from the current directory looking for go.mod.
func findProjectRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fatalf("getwd: %v", err)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fatalf("could not find project root (go.mod)")
		}
		dir = parent
	}
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "testgen: "+format+"\n", args...)
	os.Exit(1)
}
