// Code generated by testgen; DO NOT EDIT.

package crosswire

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_CrossWire(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "placeholder",
		RoundTrip:         false,
		NegativeDetection: "",
		ExpectedLossClass: "",
		SkipTests:         []string{"Detect", "DetectNegative", "Ingest", "Enumerate", "ExtractIR", "EmitNative", "RoundTrip"},
	}
}
