// Code generated by testgen; DO NOT EDIT.

package osis

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_OSIS(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<osis>\n  <osisText osisIDWork=\"Test\" xml:lang=\"en\">\n    <header><work osisWork=\"Test\"><title>Test</title></work></header>\n    <div type=\"book\" osisID=\"Gen\">\n      <p><verse osisID=\"Gen.1.1\"/>In the beginning God created the heavens and the earth.</p>\n    </div>\n  </osisText>\n</osis>",
		RoundTrip:         false,
		NegativeDetection: "<?xml version=\"1.0\"?>\n<catalog><item>Not OSIS</item></catalog>",
		ExpectedLossClass: "L0",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
