// Code generated by testgen; DO NOT EDIT.

package tei

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_TEI(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<TEI xmlns=\"http://www.tei-c.org/ns/1.0\">\n  <teiHeader><fileDesc><titleStmt><title>Test</title></titleStmt><publicationStmt><p>Test</p></publicationStmt><sourceDesc><p>Test</p></sourceDesc></fileDesc></teiHeader>\n  <text><body><div type=\"book\" n=\"Gen\"><div type=\"chapter\" n=\"1\"><ab n=\"Gen.1.1\">In the beginning God created the heavens and the earth.</ab></div></div></body></text>\n</TEI>",
		RoundTrip:         false,
		NegativeDetection: "<?xml version=\"1.0\"?>\n<catalog><item>Not TEI</item></catalog>",
		ExpectedLossClass: "L1",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
