// Code generated by testgen; DO NOT EDIT.

package markdown

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_Markdown(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "---\ntitle: \"Genesis\"\nlanguage: \"en\"\nbook: \"Gen\"\n---\n\n## Chapter 1\n\n**1** In the beginning God created the heavens and the earth.\n**2** And the earth was without form, and void.\n",
		RoundTrip:         false,
		NegativeDetection: "This is plain text, not markdown Bible content.",
		ExpectedLossClass: "L1",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
