// Code generated by testgen; DO NOT EDIT.

package theword

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_TheWord(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "In the beginning God created the heavens and the earth.\nAnd the earth was without form, and void.\nAnd God said, Let there be light: and there was light.\nAnd God saw the light, that it was good.\nAnd God divided the light from the darkness.\nAnd God called the light Day, and the darkness he called Night.\nAnd the evening and the morning were the first day.\nAnd God said, Let there be a firmament in the midst of the waters.\nAnd God made the firmament.\nAnd God called the firmament Heaven.\nAnd the evening and the morning were the second day.\nAnd God said, Let the waters be gathered together.\n",
		RoundTrip:         true,
		NegativeDetection: "",
		ExpectedLossClass: "L0",
		SkipTests:         []string{"DetectNegative"},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
