// Code generated by testgen; DO NOT EDIT.

package html

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_HTML(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "<html><body><span class=\"verse\" data-verse=\"1\">In the beginning God created the heavens and the earth.</span></body></html>",
		RoundTrip:         false,
		NegativeDetection: "<html><body><p>Hello world</p></body></html>",
		ExpectedLossClass: "L1",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
