// Code generated by testgen; DO NOT EDIT.

package json

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_JSON(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "{\"meta\":{\"id\":\"test\",\"title\":\"Test Bible\",\"version\":\"1.0\"},\"books\":[{\"id\":\"GEN\",\"name\":\"Genesis\",\"order\":1,\"chapters\":[{\"number\":1,\"verses\":[{\"book\":\"GEN\",\"chapter\":1,\"verse\":1,\"text\":\"In the beginning God created the heavens and the earth.\",\"id\":\"GEN.1.1\"}]}]}],\"verses\":[]}",
		RoundTrip:         true,
		NegativeDetection: "{\"name\": \"not a bible\"}",
		ExpectedLossClass: "L0",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "test",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
