// Code generated by testgen; DO NOT EDIT.

package file

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_File(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "In the beginning God created the heavens and the earth.",
		RoundTrip:         false,
		NegativeDetection: "",
		ExpectedLossClass: "",
		SkipTests:         []string{"DetectNegative", "ExtractIR", "EmitNative", "RoundTrip"},
	}
}
