// Code generated by testgen; DO NOT EDIT.

package xml

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_XML(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<bible>\n  <book name=\"Genesis\">\n    <chapter number=\"1\">\n      <verse number=\"1\">In the beginning God created the heavens and the earth.</verse>\n    </chapter>\n  </book>\n</bible>",
		RoundTrip:         false,
		NegativeDetection: "<?xml version=\"1.0\"?>\n<catalog><item>Not a Bible</item></catalog>",
		ExpectedLossClass: "L1",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
