// Code generated by gen_versification.py. DO NOT EDIT.

package versdata

import (
	"embed"
	"encoding/json"
	"fmt"
	"sync"
)

//go:embed *.json
var versData embed.FS

// VersificationData represents parsed versification data.
type VersificationData struct {
	ID      string     `json:"id"`
	OTBooks []BookData `json:"ot_books"`
	NTBooks []BookData `json:"nt_books"`
	OTCount int        `json:"ot_count"`
	NTCount int        `json:"nt_count"`
}

// BookData represents a book's versification info.
type BookData struct {
	Name     string `json:"name"`
	OSIS     string `json:"osis"`
	Chapters []int  `json:"chapters"`
}

var (
	versCache = make(map[string]*VersificationData)
	versMu    sync.RWMutex
)

// Load loads versification data by ID.
func Load(id string) (*VersificationData, error) {
	// Normalize ID
	normalized := normalizeID(id)

	versMu.RLock()
	if data, ok := versCache[normalized]; ok {
		versMu.RUnlock()
		return data, nil
	}
	versMu.RUnlock()

	versMu.Lock()
	defer versMu.Unlock()

	// Double-check after acquiring write lock
	if data, ok := versCache[normalized]; ok {
		return data, nil
	}

	// Load from embedded data
	filename := normalized + ".json"
	content, err := versData.ReadFile(filename)
	if err != nil {
		return nil, fmt.Errorf("versification %q not found", id)
	}

	var data VersificationData
	if err := json.Unmarshal(content, &data); err != nil {
		return nil, fmt.Errorf("failed to parse versification %q: %w", id, err)
	}

	versCache[normalized] = &data
	return &data, nil
}

// versIDAliases maps every accepted input alias to its canonical file-name ID.
// The empty string maps to "kjv" (the default versification).
var versIDAliases = map[string]string{
	// KJV family
	"":         "kjv", // Default to base KJV (39 OT + 27 NT)
	"KJV":      "kjv",
	"kjv":      "kjv",
	"KJVA":     "kjva", // KJV with Apocrypha (53 OT + 27 NT)
	"kjva":     "kjva",
	// Vulgate
	"Vulgate": "vulg",
	"Vulg":    "vulg",
	"vulg":    "vulg",
	// Protestant modern translations
	"NRSV":  "nrsv",
	"nrsv":  "nrsv",
	"NRSVA": "nrsva",
	"nrsva": "nrsva",
	// Greek / Hebrew manuscripts
	"LXX":       "lxx",
	"lxx":       "lxx",
	"MT":        "leningrad",
	"mt":        "leningrad",
	"Leningrad": "leningrad",
	// Eastern traditions
	"Orthodox": "orthodox",
	"orthodox": "orthodox",
	// Catholic traditions
	"Catholic":  "catholic",
	"catholic":  "catholic",
	"Catholic2": "catholic2",
	"catholic2": "catholic2",
	// German / Reformation traditions
	"Luther":  "luther",
	"luther":  "luther",
	"German":  "german",
	"german":  "german",
	// Slavic tradition
	"Synodal":     "synodal",
	"synodal":     "synodal",
	"SynodalProt": "synodalprot",
	"synodalprot": "synodalprot",
	// French traditions
	"Calvin":  "calvin",
	"calvin":  "calvin",
	"DarbyFr": "darbyfr",
	"darbyfr": "darbyfr",
	"Segond":  "segond",
	"segond":  "segond",
}

// normalizeID normalizes versification IDs to match file names.
func normalizeID(id string) string {
	if canonical, ok := versIDAliases[id]; ok {
		return canonical
	}
	return id
}

// List returns all available versification IDs.
func List() []string {
	entries, _ := versData.ReadDir(".")
	var ids []string
	for _, e := range entries {
		name := e.Name()
		if len(name) > 5 && name[len(name)-5:] == ".json" {
			ids = append(ids, name[:len(name)-5])
		}
	}
	return ids
}
