// Code generated by testgen; DO NOT EDIT.

package txt

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_TXT(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "Gen 1:1 In the beginning God created the heavens and the earth.\nGen 1:2 And the earth was without form, and void.",
		RoundTrip:         false,
		NegativeDetection: "This is just a random text file with no verse references.",
		ExpectedLossClass: "L3",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
