// Code generated by testgen; DO NOT EDIT.

package zefania

import (
	"testing"

	ftesting "github.com/JuniperBible/Public.Tool.JuniperBible/core/formats/testing"
)

func TestFormat_Zefania(t *testing.T) {
	ftesting.RunFormatTests(t, newTestCase())
}

func newTestCase() ftesting.FormatTestCase {
	return ftesting.FormatTestCase{
		Config:            Config,
		SampleContent:     "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<XMLBIBLE biblename=\"Test\">\n  <BIBLEBOOK bnumber=\"1\" bname=\"Genesis\">\n    <CHAPTER cnumber=\"1\">\n      <VERS vnumber=\"1\">In the beginning God created the heavens and the earth.</VERS>\n    </CHAPTER>\n  </BIBLEBOOK>\n</XMLBIBLE>",
		RoundTrip:         false,
		NegativeDetection: "<?xml version=\"1.0\"?>\n<catalog><item>Not Zefania</item></catalog>",
		ExpectedLossClass: "L0",
		SkipTests:         []string{},
		ExpectedIR: &ftesting.IRExpectations{
			ID:               "",
			MinDocuments:     1,
			MinContentBlocks: 1,
		},
	}
}
